config/routes.rb
Rails.application.routes.draw do
  get 'user_events', to: 'users#my_events'

  root  to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'invitations', to: 'invitations#new'
  post 'invitations', to: 'invitations#create'
  root  to: 'events#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  resources :users, only: [:show,:new,:create]
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator , class_name: 'User'
	has_many :invitations , foreign_key: :attended_event_id
	has_many :attendees, through: :invitations , source: :attendee

	validates :title, presence: true
	validates :description, presence: true
	validates :date, presence: true

  
  scope :upcoming, ->	{where('date > ?', Time.now ).order('date ASC')}
 

  
  scope :past, ->	{where('date < ?', Time.now ).order('date DESC')}


  
end

app/models/invitation.rb
class Invitation < ApplicationRecord
	belongs_to :attendee , class_name: 'User'
	belongs_to :event_attended,foreign_key: :attended_event_id, class_name: 'Event'

	

	def self.already_invited(user,event)
		self.where("attendee_id = ? and attended_event_id=?",user.id,event.id).any?
	end


	
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events , foreign_key: :creator_id, class_name: 'Event'
  has_many :invitations , foreign_key: :attendee_id 
  has_many :attended_events, through: :invitations, source: :event_attended

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true , length: {minimum:6}
  validates :password, presence: true , length: {minimum:6}

  has_secure_password
  def name_with_initial
  	"#{name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
	include InvitationsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :correct_user , only: [:update,:edit,:destroy]

  def index

      if request.fullpath == '/events'
      @events = Event.all.order('date DESC')
    elsif params[:upcoming]
      @events = Event.upcoming
    elsif params[:past]
      @events = Event.past
    end
  	 
  end

  def new
  	@event = Event.new
    
  end

  def create
  	@event = current_user.created_events.build(strong_params)
  	if @event.save
  		flash[:success] = 'Event created'
  		redirect_to events_path
  	else
  		render 'new'
  	end
  end

  def show
  	@event = Event.find_by(id: params[:id])
    @invitations = Invitation.new
    @user = User.new
  	@list_of_attendees = @event.attendees
  end

  def edit
    
  end

  def update
    @event = current_user.created_events.update(strong_params)
    if @event.save
      flash[:success] = 'Event updated'
      redirect_to @event
    else
      flash.now[:danger] = 'Update failed'
      render 'edit'
    end

  end

  def destroy

  end
    
  

  private

  def correct_user
    @event=current_user.created_events.find_by(id: params[:id])
    redirect_to root_url if @event.nil?
  end

  #def paginate
    #.paginate(page: params[:page], :per_page => 8)
  #end
  

  def strong_params
    params.require(:event).permit(:description,:location,:title, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
  	
  end

  def create
  	event = Event.find_by(id: params[:event][:id])
  	user = User.find_by(id: params[:user][:id])
    invitation = Invitation.new
  	if Invitation.already_invited(user,event)
  		redirect_to event_path(event) 	
      flash[:danger] = 'Friend is alredy invited'
  	else
  	  build_invitation(user,event)
	  end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
		@user = User.new
	end

	def create
		user = User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			log_in(user)
			redirect_to events_path
		else
			flash.now[:danger]= 'Wrong email/password'
			render 'new'
		end
		
	end

	def destroy
      log_out
      redirect_to root_path
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find_by(id: params[:id])
  	
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(strong_params)
  	if @user.save
  		flash[:success] = 'New user is created'
      log_in @user
  		redirect_to events_path
  	else
  		#flash.now[:danger] = 'There is error in your form'
  		render 'users/new'
  	end
  end



  def my_events
    @events = current_user.created_events
    if params[:request] || request.fullpath == 'user_events'
      @events
    elsif params[:upcoming]
      @events = current_user.attended_events.upcoming
    elsif params[:past]
      @events = current_user.attended_events.past
    end
      
  end

  def strong_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/events_helper.rb
module EventsHelper
	def format_time(time)
		time.strftime("%H:%M%p")
	end

	def format_date(date)
		date.strftime("%a,%d %b %Y")
	end

	

end

app/helpers/invitations_helper.rb
module InvitationsHelper
	
	def build_invitation(user,event)
	    if user.invitations.build(attended_event_id: event.id).save
	  	  #flash[:success]= 'Friend is invited'
	  	  redirect_to events_path
	    else
	  	  render event_path(event)
	    end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
	  @current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
	  session.delete(:user_id)
	  @current_user = nil
	end

	def correct_user
		current_user.id == Event.find_by(id: params[:id]).creator.id
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_card.html.erb
<% @events.each do |event| %>
    <a href="<%= event_path(event.id)%>">
    <section class="event-box">
      <div class="event-heading">
        <h4><%= event.title.capitalize %></h4>
      </div>
    </a>
    <div class="event-content">
      <p><%=event.description.truncate(50)%></p>
      <p class="host-name">By <%=event.creator.name %></p>
        <ul>
          <li>
            <i class="icon fa fa-map-marker"></i><span><%= event.location %></span>
          </li>
          <li>
            <i class="icon fa fa-calendar-o"></i><span><%= "#{format_date(event.date)} at #{format_time(event.date)}"%> </span>
          </li>
        </ul>
    </div>
    </section>

<% end %>  

app/views/events/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Update Event</h1>
    <%= form_for(@event) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title,class: "form-control" %><br>
 
      <%= f.label :description %>
      <%= f.text_area :description,class: "form-control" %><br>

      <%= f.label :location %>
      <%= f.text_field :location,class: "form-control" %><br>

      <%= f.label :date_and_time %><br>
  	
  	  <%= f.datetime_select :date, :ampm => true,
  								 :minute_step =>15,
  								 :start_year => Time.now.year,
  								 :start_month => Time.now.month,
  								 :start_day => Time.now.day ,class: "form-control"
  								  %><br><br>
    
      <%= f.submit 'Update event', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class='filter row'>
  <div class="col-sm-4 col-sm-offset-3">
    <div class="btn-group btn-group-justified">
      <%= link_to "Upcoming Events", events_path(:upcoming => true), class: 'btn btn-info btn-sm' %>
      <%= link_to "Past", events_path(:past => true), class: 'btn btn-info btn-sm' %>
    </div>
  </div>
</div>


<div class="event-index row">
  <div class="col-sm-6 col-sm-offset-3">
  <%= render 'events/event_card' %>
  </div>
</div>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= form_for @event do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit 'Create event' %>
<% end %>

app/views/events/show.html.erb
<div class="event-index row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Events Page</h1>
    <a href="<%= event_path(@event)%>">
    <section class="event-box">
      <div class="event-heading">
        <h4><%= @event.title.capitalize %></h4>
      </div>
    </a>
    <div class="event-content">
      <p><%= @event.description.truncate(50)%></p>
      <p class="host-name">By <%= @event.creator.name %></p>
        <ul>
          <li>
            <i class="icon fa fa-map-marker"></i><span><%= @event.location %></span>
          </li>
          <li>
            <i class="icon fa fa-calendar-o"></i><span><%= "#{format_date(@event.date)} at #{format_time(@event.date)}"%> </span>
          </li>
        </ul>
        <% if logged_in? && correct_user %>
        <%= link_to 'Edit event', edit_event_path(@event) %>
        <% else %>
        <% end %>
    </div>
    </section>
 
  </div>
</div>

<div class="col-sm-6 attend-box col-sm-offset-3">
		<h3 class="attending-head"><i class="fa fa-list"></i>Users Attending</h3>
		  <% @list_of_attendees.each do |attende| %>
			<ul class="guest-list">
				<li><%= attende.name %></li>
			</ul>
			
		  <% end %>     
</div>

<% if logged_in? %>
<div class="col-sm-6 col-sm-offset-3">
      <%= form_for [@event,@user] , :url => {:action=>'create', :controller=>'invitations'},:html => {:class =>'InvitationsController', :method => 'POST'} do |f| %>
  
      <%= hidden_field(:event,:id)  %>
    <div class='form-group'>
      <%= f.label :select_friend, class: 'form-control' %>
      <%= f.collection_select( :id, User.all, :id, :name, {class: 'form-control'}) %>
    
     <%= f.button 'Invite a friend',class: 'form-control ' %>
    </div>
   <% end %>
</div> 
<% else %>
<% end %>

app/views/invitations/new.html.erb
<h1>Invitations#new</h1>
<p>Find me in app/views/invitations/new.html.erb</p>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class=" footer fixed-bottom">

  <div class="footer-copyright text-center py-3"><p>© 2018 Copyright: Agon Idrizi</p>
    
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Private Events', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
     <% if logged_in? %>
     	<li><%= link_to "New event", new_event_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "My events", user_events_path %></li>
        <li><%= link_to "About", about_url %></li>
        <li><%= link_to "Log Out", logout_url, method: :delete %></li>
     <% else %>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Login", login_path %></li>
     <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  
  <body>
  <div class="container-navbar">
    <%= render 'layouts/navbar' %>
  </div>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        
      <% end %>

    <%= yield %>
  <div class="container-footer">
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h3>Welcome to Private Events!</h3>

<h4>Tips</h4>
<p>See a list of all events by clicking Events tab</p>
<p>You can make new events by clicking New event tab</p>
<p>Click My events tab to view all of your events,including that you are hosting, your past and incoming events</p>
<p>View a singular event by clicking on any event . You can invite other users by selecting a user from the dropdown menu and clicking the invite button</p>

app/views/static_pages/home.html.erb
<div class='home fluid-container'>
   <div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<div class="focus-container">
			<div class="blur"></div>
				<div class="focus-box">
				<% if logged_in? %>
					<h1>Welcome</h1>
					<a class="btn btn-lg btn-success" href="/events">All Events!</a>
				<% else %>
					<h1>Sign up</h1>
					<a class="btn btn-lg btn-success" href="/users/new">Sign up now!</a>
				<% end %>
				</div>
		  </div>
	  </div>
  </div>
</div>

app/views/users/my_events.html.erb
<div class='filter row'>
  <div class="col-sm-4 col-sm-offset-3">
    <div class="btn-group btn-group-justified">
      <%= link_to "Upcoming", user_events_path(:upcoming => true), class: 'btn btn-info btn-sm' %>
      <%= link_to "Past", user_events_path(:past => true), class: 'btn btn-info btn-sm' %>
      <%= link_to "Created events", user_events_path(:host => 'host'), class: 'btn btn-info btn-sm' %>
    </div>
  </div>
</div>




<div class="event-index row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= render 'events/event_card' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 form-new-user col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name,class: "form-control" %><br>
 
      <%= f.label :email %>
      <%= f.email_field :email,class: "form-control" %><br>

      <%= f.label :password %>
      <%= f.password_field :password,class: "form-control" %><br>

      <%= f.label :password_confirmation %><br>
  	
  	  <%= f.password_field :password_confirmation ,class: "form-control" %><br><br>
    
      <%= f.submit 'Signup', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div> 

app/views/users/show.html.erb
<h4><%= @user.name %></h4>